### ISSUE TITLE
JSX in JS

### ISSUE THREAD

**Issue by michal-laskowski** [matthewmueller/jsx#1]
behaves strangely when parsing e.g. code like this
```
<div>{h.components( [ { field: x => "(<><button>PUSH_ME</button></>)", label: "Actions"} ])}</div>
```
1. treats string as JSX
2. cuts off "}" from JS code of array item
3. does not treat "])}" as a fragment of Expression but as text

similarly when we change string to JSX.

it works correctly if we extract this piece to a variable (it will not be inside a JSX tag)

**Comment by matthewmueller** [comment]
Good call! Just fixed this issue.

**Comment by michal-laskowski** [comment]
@matthewmueller is it possible to make it work also for version with JSX in JSX?

<div>{h.components( [ { field: x => (<><button>PUSH_ME</button></>), label: "Actions"} ])}</div>

**Comment by matthewmueller** [comment]
Hmm, I'm not following, 

```
export default () =>{
  return <div>{h.components( [ { field: x => (<>PUSH_ME), label: "Actions"} ])}</div>
}
```

Is not valid JSX. Did you mean?

```
export default () =>{
  return <div>{h.components( [ { field: x => (<>PUSH_ME</>), label: "Actions"} ])}</div>
}
```
